# server yaml configure file
app_name : "ECHO-SERVER"
host : "127.0.0.1"
ports : ["10000", "20000"]
profile_port : 10086

# session
# client与server之间连接的超时时间
session_timeout : "20s"
session_number : 700

# app
fail_fast_timeout : "3s"

# tcp
getty_session_param:
    compress_encoding : true
    tcp_no_delay : true
    tcp_keep_alive : true
    keep_alive_period : "120s"
    tcp_r_buf_size : 262144
    tcp_w_buf_size : 524288
    pkg_rq_size : 1024
    pkg_wq_size : 512
    tcp_read_timeout : "1s"
    tcp_write_timeout : "5s"
    wait_timeout : "1s"
    max_msg_len : 128
    session_name : "echo-server"

task_queue_length : 1024
task_queue_number : 20
task_pool_size : 1000